server:
  port: 9301
spring:
  application:
    name: admin-server
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver1.com:8001/eureka/,http://eurekaserver2.com:8002/eureka/,http://test:test@security-eurekaserver.com:8003/eureka/
