server:
  port:
    8801
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver1.com:8001/eureka/,http://eurekaserver2.com:8002/eureka/,http://test:test@security-eurekaserver.com:8003/eureka/  #配置注册中心地址

#Zuul和Eureka结合使用，可以实现路由的自动配置，自动配置的路由以服务名称为匹配路径
zuul:
  prefix: /proxy #给网关路由添加前缀
  #Zuul在请求路由时，默认会过滤掉一些敏感的头信息，以下配置设置为空可以防止路由时的Cookie及Authorization的丢失
  sensitive-headers: Cookie,Set-Cookie,Authorization #默认配置，设置为空不过滤
  add-host-header: true #设置为true重定向是会添加host请求头
  routes:
    data-service:
      path: /dataService/**
    feign-service:
      path: /feignService/**
  ignored-services: data-service,feign-service #不想使用默认的路由规则，需要关闭
  #禁用某过滤器,格式为过滤器名.过滤类型.disable=true
  PreLogFilter:
    pre:
      disable: true #控制是否禁用过滤器
#开启查看路由的端点 通过/acatuator/routes查看,通过/actuator/routes/details查看详细信息
management:
  endpoints:
    web:
      exposure:
        include: 'routes'
