server:
  port: 8003 #指定运行端口
spring:
  application:
    name: eureka-server #指定服务名称
  security:
    user:
      name: test
      password: test
eureka:
  instance:
    hostname: security-eurekaserver.com #指定主机地址
  client:
    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: false #指定是否要注册到注册中心（注册中心不需要开启）
    service-url:
      defaultZone: http://eurekaserver1.com:8001/eureka/,http://eurekaserver2.com:8002/eureka/ #配置注册中心地址