server:
  port: 8301
spring:
  application:
    name: ribbon-service
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver1.com:8001/eureka/,http://eurekaserver2.com:8002/eureka/,http://test:test@security-eurekaserver.com:8003/eureka/  #配置注册中心地址
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
service-url:
  data-service-url: http://data-service